-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.flyway_schema_history
(
    installed_rank integer NOT NULL,
    version character varying(50) COLLATE pg_catalog."default",
    description character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    script character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    checksum integer,
    installed_by character varying(100) COLLATE pg_catalog."default" NOT NULL,
    installed_on timestamp without time zone NOT NULL DEFAULT now(),
    execution_time integer NOT NULL,
    success boolean NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.perfil
(
    perfil_id serial NOT NULL,
    ativo boolean NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perfil_pkey PRIMARY KEY (perfil_id),
    CONSTRAINT perfil_unique UNIQUE (nome)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.perfil_permissao
(
    permissao_id integer NOT NULL,
    perfil_id integer NOT NULL,
    CONSTRAINT perfil_permissao_pkey PRIMARY KEY (permissao_id, perfil_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.permissao
(
    permissao_id serial NOT NULL,
    endpoint character varying(255) COLLATE pg_catalog."default",
    expressao_regular character varying(255) COLLATE pg_catalog."default",
    nome_componente character varying(255) COLLATE pg_catalog."default",
    tipo_permissao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    identificador character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT permissao_pkey PRIMARY KEY (permissao_id),
    CONSTRAINT permissao_unique UNIQUE (identificador)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    usuario_id bigserial NOT NULL,
    ativo boolean NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    login character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (usuario_id)
)
WITH (
    OIDS = FALSE
);

CREATE TABLE IF NOT EXISTS public.usuario_perfil
(
    perfil_id integer NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT usuario_perfil_pkey PRIMARY KEY (perfil_id, usuario_id)
)
WITH (
    OIDS = FALSE
);

ALTER TABLE IF EXISTS public.perfil_permissao
    ADD CONSTRAINT fkae12hkpoxg80wb2dn1cog5y55 FOREIGN KEY (perfil_id)
    REFERENCES public.perfil (perfil_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.perfil_permissao
    ADD CONSTRAINT fkdjkaj85jgqb28eu3a4n9siqee FOREIGN KEY (permissao_id)
    REFERENCES public.permissao (permissao_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_perfil
    ADD CONSTRAINT fk22cgfn0obntlvqyfn33pyk24d FOREIGN KEY (perfil_id)
    REFERENCES public.perfil (perfil_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_perfil
    ADD CONSTRAINT fknrjqnbylalt4ykxbcef24f57w FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (usuario_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;